config/routes.rb
Bloggable::Engine.routes.draw do

  resources :articles

end

app/models/bloggable/application_record.rb
module Bloggable
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/bloggable/article.rb
module Bloggable
  class Article < ApplicationRecord

    include Gallerify
    include AASM

    extend FriendlyId
    friendly_id :title, use: :slugged


    belongs_to :bloggable, polymorphic: true, touch: true, optional: true
    belongs_to :author, class_name: "User", optional: true

    has_many :comments, dependent: :destroy

    default_scope { order("created_at desc") }

    aasm do
      state :draft, :initial => true
      state :published
      state :archived

      event :publish do
        transitions :from => :draft, :to => :published
      end

      event :archive do
        transitions :from => [:draft, :published], :to => :archived
      end
    end

    def set_transition_timestamp(given_status, time=Time.now)
      timestamp_field = "#{given_status}_at".to_sym
      self[timestamp_field] = time
    end
  end
end

app/models/bloggable/comment.rb
module Bloggable
  class Comment < ApplicationRecord

    belongs_to :article
    belongs_to :commenter, class_name: "User"
  end
end

app/controllers/bloggable/application_controller.rb
module Bloggable
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/bloggable/articles_controller.rb
# require_dependency "bloggable/application_controller"

module Bloggable

  class ArticlesController < ::ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :set_bloggable, only: :create
    before_action :authenticate_user!, except: [:show, :index]


    def index
      @articles = Article.all
    end

    def show
    end

    def new

      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params.merge(bloggable_type: @bloggable.class.to_s, bloggable_id: @bloggable.id))
      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private

      def set_bloggable
        url = URI(request.referrer).path.split("/articles").first.split("/")

        @bloggable = url[-2] ? url[-2].classify.safe_constantize.find(url[-1]) : current_user
      end

      def set_article
        @article = Article.friendly.find(params[:id])
      end

      def article_params
        params.require(:article).permit!#(:title, :text, :bloggable_id, :bloggable_type)
      end
  end
end

app/helpers/bloggable/application_helper.rb
module Bloggable
  module ApplicationHelper
  end
end

app/helpers/bloggable/articles_helper.rb
module Bloggable
  module ArticlesHelper
  end
end

app/views/bloggable/articles/_form.html.haml
= form_for(article) do |f|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit

app/views/bloggable/articles/edit.html.haml
%h1 Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/bloggable/articles/index.html.haml
%p#notice= notice
%h1 Articles
%table
  %thead
    %tr
      %th Title
      %th Text
      %th{:colspan => "3"}
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.title
        %td= article.text
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Article', bloggable.new_article_path

app/views/bloggable/articles/new.html.haml
= @bloggable

%h1 New Article
= render 'form', article: @article
= link_to 'Back', articles_path

app/views/bloggable/articles/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @article.title
%p
  %strong Text:
  = @article.text
= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path